CREATE TABLE employee (
idEmployee INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
firstName VARCHAR(20) NOT NULL,
lastName VARCHAR(20) NOT NULL,
phone VARCHAR(15) NOT NULL,
mail VARCHAR(30) NOT NULL,
password TEXT NOT NULL,
birthDate DATE NOT NULL,
hireDate DATE NOT NULL,
IBAN VARCHAR(34) NOT NULL,
idRelation INTEGER NOT NULL, 
idWorkplace INTEGER NOT NULL, 
isWorking INTEGER NOT NULL, 
idProfession INTEGER NOT NULL,
FOREIGN KEY(idWorkplace) REFERENCES workplace(idWorkplace),
FOREIGN KEY(idProfession) REFERENCES profession(idProfession)
);

CREATE TABLE relationEmployee (
idRelation INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
idEmployee INTEGER NOT NULL,
idReferent INTEGER NOT NULL,
FOREIGN KEY(idEmployee) REFERENCES employee(idEmployee) ON DELETE CASCADE,
FOREIGN KEY(idReferent) REFERENCES employee(idEmployee) ON DELETE CASCADE
);

CREATE TABLE workplace (
idWorkplace INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name VARCHAR(40) NOT NULL,
adress VARCHAR(40) NOT NULL,
phone VARCHAR(15) NOT NULL,
mail VARCHAR(30) NOT NULL,
type VARCHAR(20) NOT NULL
);

CREATE TABLE profession (
idProfession INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name VARCHAR(20) NOT NULL,
description VARCHAR(40),
salary INTEGER NOT NULL
);

CREATE TABLE relationWorkplaceSupplier (
idRelation INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
idWorkplace INTEGER NOT NULL,
idSupplier INTEGER NOT NULL,
FOREIGN KEY(idWorkplace) REFERENCES workplace(idWorkplace) ON DELETE CASCADE,
FOREIGN KEY(idSupplier) REFERENCES supplier(idSupplier) ON DELETE CASCADE
);

CREATE TABLE supplier (
idSupplier INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
firstName VARCHAR(20) NOT NULL,
lastName VARCHAR(20) NOT NULL,
idProduct INTEGER NOT NULL,
phone VARCHAR(20) NOT NULL,
adress VARCHAR(40) NOT NULL,
mail VARCHAR(40),
FOREIGN KEY(idProduct) REFERENCES product(idProduct) ON DELETE CASCADE
);

CREATE TABLE product (
idProduct INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name VARCHAR(40) NOT NULL
);